language: python
reset_minion: true

python:
  - 2.7
  # - 3.2
  # - 3.3
  # - 3.4
  # - pypy
  
install:
- sudo apt-get install python-numpy
- sudo apt-get install python-matplotlib
- sudo apt-get install python-yaml
- sudo apt-get install wkhtmltopdf
- sudo apt-get install graphviz
- pip install -r requirements.txt
- pip install numpy
# - pip install scipy 

- "python -c 'import contracts; print contracts.__version__'"
- "python -c 'import quickapp;  print  quickapp.__version__'"
- "python -c 'import compmake;  print  compmake.__version__'"
- "python -c 'import reprep;    print    reprep.__version__'"

- python setup.py develop

script:
# run first without contracts
- make comptests-run-parallel-nocontracts
- make -C examples/example-catalogue
- make -C examples/example-battery
# the run with contracts
- make clean comptests-run-parallel
