#!/bin/bash
set -e
set -x
docname=${1%.*}
echo Docname: ${docname}

libraries=~/env_mcdp/src/mcdp/src/mcdp_data/libraries

mcdp-render -D ${libraries} ${docname}

out_html=out/mcdp_render/${docname}.html

#./extract-assets ${out_html} ${out_html}

prince -o ${docname}.pdf  ${out_html}


echo Written on  ${docname}.pdf