#!/bin/bash
set -e
set -x
docname=${1%.*}
echo Docname: ${docname}

mcdp-render ${docname}

out_html=out/mcdp_render/${docname}.html

./extract-assets ${out_html} ${out_html}

prince -o ${docname}.pdf  ${out_html}


echo Written on  ${docname}.pdf