dirname="../../src/mcdp_data/libraries/examples/example-battery.mcdplib"

all:	
	mcdp-plot -d $(dirname) --out battery-out_expected3 battery_minimal
	mcdp-plot -d $(dirname) --out battery-out_expected3 battery
